### ISSUE TITLE
forked

### ISSUE THREAD

**Issue by martin-raden** [AlexanderMattheis/Cross-Dating#1]
Moin Alex,

hab das repo mal ins BackofenLab geforkt. Wenn du willst, können wirs auch komplett dort hosten und ich trag ich als collaborator mit adminrechten ein. dann würde man sich den doppelmoppel sparen. kannst aber auch hier hosten, no prob, wie es dir am besten gefällt.

Danke,
der Martin

**Comment by AlexanderMattheis** [comment]
Ich denke es passt so. Du hast es ja schon geforked. :)
Ich sage am Präsentationstermin Bescheid, 
falls ich noch irgendwelche Änderungen durchgeführt habe.
Dann brauchst eventuell einmal zu aktualisieren und fertig.

Hinweis: Ich habe nur die Testbeispiele für die Interfaces hochgeladen,
meine 200 MB an vorberechneten Scores wollte ich da nicht mit reintun,
da es sonst nur das Repository aufbläht und es nicht so gern gesehen wird,
wenn Rohdateien und nicht Quellcode hochgeladen wird. 
Naja, ich packe die dann auf die gebrannten CD-Roms 
(sonst sind die Visualisierungen nicht ausführbar). :)

Gruß, Alex
